# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "c1b8104a630b97c553367dba11a66a96f3b07f25d6797b7ca265f7f90f14261d"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0dbf0b59645f2aeac7bd0842d2d50cde190cb393a52f455902405b63083aa15"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fad43341d01623da08f5ba610b631ac09225136f439798f971328da52dfd561d"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "170cfe0cc2735633b509e17c4590c0add072ddaa27fb1693242494a1ca44698c"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Read your Pulse analytics from the terminal"
  homepage "https://ciphera.net/products/pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"

  # No zap stanza required

end
