# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "1.1.2"

  on_macos do
    on_intel do
      sha256 "07fa482d058bca6de45390186afadb2e89ba434883f8df1f47993c288ca710e3"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "18fb659bf750fad18130898407bcd29ebb8242de6f279b69854a0bd1f22dd7b4"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ca258135b4e723b0dfff2723e1df58541c5f58b77af482ed8219f0949fa02bfd"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "95426d650e24d88e77e250fdcdd1922fd1a2f255fc4ce283735d4626f3b9176d"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Read your Pulse analytics from the terminal"
  homepage "https://ciphera.net/products/pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"

  # No zap stanza required

end
