# This file was generated by GoReleaser. DO NOT EDIT.
cask "pulse" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "98b9f4ac988755f60eeafdaf8234c34d037984fba704d4eccd11b8476c9b117d"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15e8139a0397a7cc0ae8ee1a186001b823068b10f4b51fd654c489db9b16e0d7"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fafd0ab86fae110eb3dc6bed2882b108d31cf4c7eac7f888b205c5ea70e9a36d"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f05773bd7769ea49e6c03bec547052a61db3751d5fd4dd9c148b260919f2306e"
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v#{version}/pulse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pulse"
  desc "Read your Pulse analytics from the terminal"
  homepage "https://ciphera.net/products/pulse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pulse"

  # No zap stanza required

end
