# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulse < Formula
  desc "Read your Pulse analytics from the terminal"
  homepage "https://ciphera.net/products/pulse"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.0.0/pulse_1.0.0_darwin_amd64.tar.gz"
      sha256 "62bb0b39198669f22d1c02e0646e4a301fbbd851a8438e42c8ba10f2094166b2"

      define_method(:install) do
        bin.install "pulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.0.0/pulse_1.0.0_darwin_arm64.tar.gz"
      sha256 "5907c96c807309ef10ac6130caf6f121c9c56f37ee9acbbaa731ebc929e9db72"

      define_method(:install) do
        bin.install "pulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.0.0/pulse_1.0.0_linux_amd64.tar.gz"
      sha256 "cda033060a3c50ca844d4c91b3934109010924dbd760259abd4fadb8977509df"
      define_method(:install) do
        bin.install "pulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.0.0/pulse_1.0.0_linux_arm64.tar.gz"
      sha256 "382362c789c77d5cdec2f8251909bcc9a13f2d57cf07a12dfb965f6619dc0441"
      define_method(:install) do
        bin.install "pulse"
      end
    end
  end

  test do
    system "#{bin}/pulse", "--version"
  end
end
