# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pulse < Formula
  desc "Read your Pulse analytics from the terminal"
  homepage "https://ciphera.net/products/pulse"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.1.0/pulse_1.1.0_darwin_amd64.tar.gz"
      sha256 "8af40859446f3fee81d65f085e2c95261fd95a97e1331d49370d9a537c2d9e24"

      define_method(:install) do
        bin.install "pulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.1.0/pulse_1.1.0_darwin_arm64.tar.gz"
      sha256 "fd939fb41edc263a900e018e0983aab94434dedb0e47d183e2eba6b2a17eb6a0"

      define_method(:install) do
        bin.install "pulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.1.0/pulse_1.1.0_linux_amd64.tar.gz"
      sha256 "fd16e2bd7ce6204d1fde100b6c0ad14268e203839f9f97eda822a5e157c26df9"
      define_method(:install) do
        bin.install "pulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ciphera-net/pulse-cli/releases/download/v1.1.0/pulse_1.1.0_linux_arm64.tar.gz"
      sha256 "0a8e4d25e8870bd1d0f502e1c352defc04009d9b4aaf9725d23af72711e7b8bb"
      define_method(:install) do
        bin.install "pulse"
      end
    end
  end

  test do
    system "#{bin}/pulse", "--version"
  end
end
